// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnLWPODR9JrIzSQSdHveCtCuYFVqhzn54',
    appId: '1:273174365606:web:413ec401764bfe436d3b67',
    messagingSenderId: '273174365606',
    projectId: 'ditck-d0ef2',
    authDomain: 'ditck-d0ef2.firebaseapp.com',
    storageBucket: 'ditck-d0ef2.firebasestorage.app',
    measurementId: 'G-HXB8MGKHP7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC56rtyXV9VzHtkkR4_vma4zXrpKChcWcw',
    appId: '1:273174365606:android:b9b1c79a855432d46d3b67',
    messagingSenderId: '273174365606',
    projectId: 'ditck-d0ef2',
    storageBucket: 'ditck-d0ef2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmPN3x7LdBg3gSxYkLQDnsOnXb3vCUsEc',
    appId: '1:273174365606:ios:2637c4d52e0e3d0f6d3b67',
    messagingSenderId: '273174365606',
    projectId: 'ditck-d0ef2',
    storageBucket: 'ditck-d0ef2.firebasestorage.app',
    androidClientId: '273174365606-79cldbkm37a6i06f9os30el5b2f3gdau.apps.googleusercontent.com',
    iosClientId: '273174365606-t2gkhqbpj7cr6l41k4t14ar91st0ioen.apps.googleusercontent.com',
    iosBundleId: 'com.example.ditck',
  );
}
